### ISSUE TITLE
problem reading the network model from the .RData file

### ISSUE THREAD

**Issue by sdghafouri** [statnet/ergm#37]
I am trying to build an ERGM model and simulate some artificial networks from the model in the R language statnet library. When I simulate the model exactly after the building the model I can do so without any problems.

`netModel <- ergm(net ~ edges + density + triangles + gwdegree(0.25))`
`simulatedNet <- simulate(netModel, nsim=1)`

However, when I save the model in a .RData object an load it some time later I have problems. For example,

`save(netModel, file = "netModelRdata.Rdata")`
and later do the following steps
`load("netModelRdata.Rdata")`
`simulatedNet <- simulate(netModel, nsim=1)`

I get the following error:

`Error in eval(expr, envir, enclos) :` 
`  Invalid network on the LHS of the formula.`

thank you for your replies in advance.

**Comment by sgoodreau** [comment]
Hello @sdghafouri. I re-created your code, and found that I did not have a problem - both the version where I simulated immediately and the one where I saved the model, deleted it locally, loaded it, and then simulated worked just fine.  I think I may have some explanation.  First off, here is my full code:

```
library(statnet)

## Create an empty network, create a known model and estimate it, then simulate form that to get a fake network to work from
net <- network.initialize(20, directed=FALSE)
model_setup <- ergm(net~edges+gwesp(0,fixed=TRUE), target.stats=c(30, 12))
net <- simulate(model_setup)
summary(net~ edges + triangles + gwesp(0,fixed=TRUE)+gwdegree(0.25, fixed=TRUE))

## Fit model: note, edgs and density cannot both be in the model/
#netModel <- ergm(net ~ edges + density + triangles + gwdegree(0.25))
netModel <- ergm(net ~ edges + triangles + gwdegree(0.25))
simulatedNet <- simulate(netModel, nsim=1)

## Save, delete, load, simulate
save(netModel, file = "netModelRdata.Rdata")
rm(netModel)
load("netModelRdata.Rdata")
simulatedNet <- simulate(netModel, nsim=1)
```

Since you didn't include a test case, I made my own, making a toy network in the first few lines.

Then I fit the model. Note that I removed your term "density".  Edges and density are two different parametrizations of the same concept, so you cannot have both in the model.  I am in fact surprised that the model fit at all given that you had both in there! Also, the triangles term is known to be a dangerous one, and it's often better to use gwesp instead; I didn't do that here because I made a very small network for this toy case, which typically masks the problems with triangles.

Then I saved the fit, deleted it locally, re-loaded it, and simulated from it, and all was fine.

My guess is that what happened for you is not actually an issue with loading per se, but rather that you fit your model twice, and one time it converged and sometimes it didn't.  The time it did converge you simulated immediately and all was good.  The time that it didn't converge, you saved it and then loaded it again, but there were issues with the model.

So my advice is to first try all the code above and see if it works for you.  

If it doesn't work, then please respond here again.  Pleae iIf you do face the same issue, I'm guessing there's something unusual about environments going on with your setup. 

if you don't have a problem with the above, then I suggest that you revisit your model, taking out the density term and considering replacing triangles with gwesp.  You might also set fixed=TRUE for both gwesp and gwdegree.  That will give you a more stable model, at least to start, and then you can explore from there.

**Comment by sdghafouri** [comment]
Thank you for your response and careul look at my question. I also thank you for your useful comments about my model statistics.
I checked your code and it did work fine.
However the problem persist when I use my own data (even with your code), the interesting thing is when I use your network in my code it doesn't work either. I am not sure but I think there is something about the data I am using. But the question is why it only happens when I save and re-load the model?

These are my codes and data:
[githubQuestion.zip](https://github.com/statnet/ergm/files/2612326/githubQuestion.zip)

first I build the model using the buildModel.R the I try to simulate it using the simulation.R and that is where the error occurs. Just be careful to fix the directory variables that exists in the code according to your system.

and here is the sessionInfo()

`R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
[1] statnet_2016.9       sna_2.4              ergm.count_3.3.0    
[4] statnet.common_4.1.4 tergm_3.5.2          networkDynamic_0.9.0
[7] ergm_3.9.4           network_1.13.0.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19      bindr_0.1.1       magrittr_1.5     
 [4] MASS_7.3-45       tidyselect_0.2.4  lattice_0.20-33  
 [7] R6_2.2.2          rlang_0.2.1       dplyr_0.7.6      
[10] tools_3.2.3       grid_3.2.3        nlme_3.1-124     
[13] lpSolve_5.6.13    coda_0.19-1       assertthat_0.2.0 
[16] tibble_1.4.2      crayon_1.3.4      Matrix_1.2-3     
[19] bindrcpp_0.2.2    purrr_0.2.5       trust_0.1-7      
[22] glue_1.2.0        robustbase_0.93-0 DEoptimR_1.0-8   
[25] pillar_1.3.0      pkgconfig_2.0.2  `

**Comment by sgoodreau** [comment]
Thanks @sdghafouri.  It looks like my colleague can replicate your problem, but I still cannot -- so there's likely something going on about one of the package versions. She's created a small example that recreates it; we'll keep working to isolate it from here.

**Comment by sgoodreau** [comment]
Bringing some off-line conversation here, nad adding new findings:

@martinamorris found that the following code caused her the same error when using the CRAN version of all relevant packages:

```
library(ergm)
data("faux.mesa.high")
fit <- ergm(faux.mesa.high~edges+nodematch("Race"))
save(fit, file="testfit")
load("testfit")
simnet <- simulate(fit, nsims=1)
```

I tried that code on my local machine, which had the github master versions of `ergm`, `tergm`, `network`, and `statnet.common` on it, and did not get the error.  Since Martina had the problems with the CRAN versions, I just installed all of those (CRAN versions) on my machine, and still did not get the error.  My session info is below. The strange thing is that @sdghafouri and I seem to have all the same versions of the relevant statnet suite packages (not counting `statnet` proper, `sna`, `ergm.count`, and `networkDynamic`, but that's only because I didn't have them loaded at all since they aren't used here).

@martinamorris, can you send the session info for when you do get the error with your simplified code?

Note that I did get a warning:
```
> simnet <- simulate(fit, nsims=1)
Warning message:
You appear to be calling simulate.formula() directly. simulate.formula() is a method, and will not be exported in a future version of ‘ergm’. Use simulate() instead, or getS3method() if absolutely necessary. 
```

which is of course not a useful warning since I *didn't* call simulate.formula directly.  I will file a separate issue about that. I wonder if it is somehow related....

```
> sessionInfo()
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tergm_3.5.2          networkDynamic_0.9.0 ergm_3.9.4           network_1.13.0.1    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0           rstudioapi_0.8       bindr_0.1.1          magrittr_1.5         MASS_7.3-50         
 [6] tidyselect_0.2.5     lattice_0.20-35      R6_2.3.0             rlang_0.3.0.1        dplyr_0.7.8         
[11] tools_3.5.1          parallel_3.5.1       grid_3.5.1           nlme_3.1-137         lpSolve_5.6.13      
[16] coda_0.19-2          yaml_2.2.0           assertthat_0.2.0     tibble_1.4.2         crayon_1.3.4        
[21] Matrix_1.2-14        bindrcpp_0.2.2       purrr_0.2.5          trust_0.1-7          glue_1.3.0          
[26] robustbase_0.93-3    statnet.common_4.1.4 DEoptimR_1.0-8       compiler_3.5.1       pillar_1.3.0        
[31] pkgconfig_2.0.2     
```

**Comment by smjenness** [comment]
I think this has to do with an underlying R issue in how objects from the global environment are stored using the `save` function. Running the @martinamorris example, I get the same error as her. 

For the `simulate.ergm` function this has to do with a lookup problem in the environment where the LHS network object is stored, and then pulled during simulation. For me, it is looking up within the global environment, but for me that environment is not getting saved.

```r
library(ergm)
data("faux.mesa.high")
fit <- ergm(faux.mesa.high~edges+nodematch("Race"))
save(fit, file="testfit.rda")
rm(list=ls())
load("testfit.rda")
environment(fit$formula)

<environment: R_GlobalEnv>
```

 Interestingly, and coincidentally, a solution to this problem would also solve the other related one about the choosing the right starting network we were discussing elsewhere. That is, if we set the default basis network as `x$newnetwork` instead of pulling the object from the environment, it should solve this problem for good. For example:

```r
library(ergm)
data("faux.mesa.high")
fit <- ergm(faux.mesa.high~edges+nodematch("Race"))
save(fit, file="testfit.rda")
rm(list=ls())
load("testfit.rda")
simnet <- simulate(fit, nsims=1, basis = fit$newnetwork)
```

The warning message about `simulate.formula` is unrelated and @krivit has fixed this on Github master.

**Comment by sgoodreau** [comment]
Thanks @smjenness. This two-birds-with-one-stone solution is indeed attractive. @krivit, I believe that you amd @martinamorris have been in conversation about that fix?

Do you (or anyone) have any sense why I'm not getting the error when everyone else is?  Note that I also get it when I insert a `rm(list=ls())` line in the middle before loading the object. Is it because we have different versions of R? (I have `3.5.1`).

**Comment by smjenness** [comment]
What do you get when you run the last line here in a fresh R session:

```r
library(ergm)
data("faux.mesa.high")
fit <- ergm(faux.mesa.high~edges+nodematch("Race"))
save(fit, file="testfit.rda")
rm(list=ls())
load("testfit.rda")
environment(fit$formula)
```

**Comment by sgoodreau** [comment]
Hmmmm.  I get `<environment: R_GlobalEnv>`.

And it turns out that with your code (including the line `> simnet <- simulate(fit, nsims=1)` I do get the error `Error in eval(object[[2]], envir = environment(object)) :  object 'faux.mesa.high' not found`. I hadn't actually run your code; only Martina's.  And now running hers again, I do get the error.  I didn't yesterday or earlier today with either CRAN or master. But I'mve been updating all sorts of stuff while working on multiple problem diagnoses, so it's probably lost now in the sands of time what combo I had.

In either case, it looks like you've found the core issue @smjenness, as well as a proposed solution for `ergm`.

**Comment by sdghafouri** [comment]
@sgoodreau @martinamorris Thank u for the discussion, I still have the problem and I also updated my R environment as @martinamorris mentioned solved the problem for her but unfortunately, it wasn't the case for me. However, the @smjenness solution solved my problem in another way. thank u

**Comment by martinamorris** [comment]
@sdghafouri, glad to know you have a solution now.  I'm still curious to know now why this works for some of us, and not others.

When you say updating didn't solve your problem, did you try the simple example we were using:
```
library(ergm)
data("faux.mesa.high")
fit <- ergm(faux.mesa.high~edges+nodematch("Race"))
save(fit, file="testfit.rda")
load("testfit.rda")
simnet <- simulate(fit, nsims=1)
```
or just your original script?

Can you please upload your sessionInfo() post-update for us?  And are you using a Mac, Windows or *nix system?

**Comment by sgoodreau** [comment]
@dth2 has been facing some issues that may overlap with this and he spent time yesterday diagnosis his code, so I'm adding him here

**Comment by smjenness** [comment]
@martinamorris You need a `rm(list=ls()` in between `save` and `load` to replicate his workflow. That's the step that gets rid of the `faux.mesa.high` object from the global environment. I would imagine this breaks for you too.

```r
library(ergm)
data("faux.mesa.high")
fit <- ergm(faux.mesa.high~edges+nodematch("Race"))
save(fit, file="testfit.rda")
rm(list=ls())
load("testfit.rda")
simnet <- simulate(fit, nsims=1)
```

**Comment by martinamorris** [comment]
indeed it does break for me now.  thx for noticing that

**Comment by dth2** [comment]
An additional issue to note here is that saving and est object and then moving it to hyak to start simulations also drops the evnironmetal network object and generates this error.

**Comment by krivit** [comment]
@smjenness 's solution makes sense, but there is a decision we need to make. We can use, as the default `basis`, 
* `object$network`, which is the original LHS passed to `ergm()`, possibly updated by `san()`; or
* `object$newnetwork`, which is a random draw from an ERGM in the vicinity of the MLE, or a copy of `object$network` if using MPLE or CD.

`newnetwork` is better in the sense that it's already "burned in", but a user might expect that the simulation would start at the original LHS network they had passed to `ergm`. Any preferences?

In addition, we might want to make it legal to pass either a network object or a string (e.g., `"lhs"` or `"new"`) to select which object will be used.

**Comment by smjenness** [comment]
That doesn’t seem to hold if using an empty network + target stats approach for defining the LHS nw. See the discussion on the linked issue for a concrete example.

**Comment by krivit** [comment]
I think that we might be using "constraints" differently here. I use it to refer to the sample space constraints specified by the formula passed to `constraints=`. Are you using it to refer to the `target.stats=` argument passed to `ergm()`?

**Comment by smjenness** [comment]
Yes when they are functionally equivalents. For example, ~bd(maxout = 2) vs degrange(from = 3) with a target stat of 0

**Comment by martinamorris** [comment]
> @smjenness 's solution makes sense, but there is a decision we need to make. We can use,
> as the default basis,
>
>  *  object$network, which is the original LHS passed to ergm(), possibly updated by san();
>     or
>  *  object$newnetwork, which is a random draw from an ERGM in the vicinity of the MLE, or
>     a copy of object$network if using MPLE or CD.
> 
> newnetwork is better in the sense that it's already "burned in", but a user might expect
> that the simulation would start at the original LHS network they had passed to ergm. Any
> preferences?

with egocentric estimation there is no "original LHS network".  so i 
think we would want this set up as a conditional:

if estimated from  complete network, use object$network as default, but 
provide an argument (basis?) that would allow the user to specify 
$newnetwork instead

if estimated from target stats, use object$newnetwork as default (and only 
option?).

> In addition, we might want to make it legal to pass either a network object or a string
> (e.g., "lhs" or "new") to select which object will be used.

sure.
